### PR TITLE
Update ember-moment to 2.0.1

### PR DESCRIPTION
**Pull request by vasilakisfil**
I had an issue with that addon after I upgraded my ember to 0.12 and ember-cli to 0.2.7:

```
TypeError: undefined is not a function
    at Class.included (/home/vasilakisfil/Kollegorna/skl-related/skl-genombrott-ember/node_modules/ember-rl-week-picker/node_modules/ember-moment/index.js:17:15)
    at /home/vasilakisfil/Kollegorna/skl-related/skl-genombrott-ember/node_modules/ember-cli/lib/models/addon.js:241:32
    at Array.map (native)
    at Class.eachAddonInvoke (/home/vasilakisfil/Kollegorna/skl-related/skl-genombrott-ember/node_modules/ember-cli/lib/models/addon.js:239:22)
    at Class.Addon.included (/home/vasilakisfil/Kollegorna/skl-related/skl-genombrott-ember/node_modules/ember-cli/lib/models/addon.js:345:8)
    at EmberApp.<anonymous> (/home/vasilakisfil/Kollegorna/skl-related/skl-genombrott-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:312:15)
    at Array.filter (native)
    at EmberApp._notifyAddonIncluded (/home/vasilakisfil/Kollegorna/skl-related/skl-genombrott-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:307:45)
    at new EmberApp (/home/vasilakisfil/Kollegorna/skl-related/skl-genombrott-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:103:8)
    at Object.<anonymous> (/home/vasilakisfil/Kollegorna/skl-related/skl-genombrott-ember/Brocfile.js:5:11)
```

Updating the ember-moment dependency seems the only solution here..

### CODE REVIEW

**Comment by RSSchermer** [comment]
Thanks! Merging...

Will hold off on releasing a new version for a couple of days. I'm a bit behind on maintenance on this addon and its sibling addons, which I'll try to catch up on over the weekend. When that's done I'll release it as either 0.2.2 or 0.3.0 (I've not decided yet, will post back here).

**Comment by RSSchermer** [comment]
It was a bit more work than I anticipated, but I just released 0.3.0, which updated everything to work nicely with Ember release (1.13.6). It _should_ work with Ember 1.12 as well, although I haven't tested it. Let me know if you encounter problems.
